<?php

namespace Tests\Unit\Services\CartService;

use App\Models\Stock;
use App\Models\User;
use App\Services\CartService\CartService;
use Tests\TestCase;
use Str;

class CartServiceTest extends TestCase
{
    public CartService $service;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = new CartService();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testCreate(): void
    {
        /** @var Stock $stock */
        $stock  = Stock::with(['countable:id,shop_id'])->first();
        $user   = User::first();

        $data = [
            'user_id'   => $user->id,
            'owner_id'  => $user->id,
            'name'      => Str::random(6),
            'stock_id'  => $stock->id,
            'shop_id'   => $stock->countable?->shop_id,
            'quantity'  => 1,
            'price'     => $stock->rate_total_price,
            'discount'  => $stock->rate_actual_discount,
        ];

        $this->actingAs($user);

        $result = $this->service->create($data);

        $this->assertTrue(!!data_get($result, 'data.id'));
    }
}
